# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-latest':
    docker:
      - image: circleci/node:latest
    working_directory: ~/three.signal-line
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npx nyc report --reporter=lcov > coverage.lcov && npx codecov
      - run: npm run cov:check

workflows:
  version: 2
  build:
    jobs:
      - 'node-latest'
